ARG CUDA_VERSION=9.0
FROM mitmul/pynvvl:cuda-${CUDA_VERSION}

RUN apt-get update && apt-get install -y \
    python \
    python-dev \
    python-pip \
    python-tk \
    python-dbg \
    ffmpeg \
    gdb \
    gawk \
    chrpath

RUN pip install \
    cython \
    numpy \
    matplotlib \
    imageio

ARG CUPY_PACKAGE_NAME
RUN pip install ${CUPY_PACKAGE_NAME}
